/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package games;

import games.snakegame.*;
import games.flappyBird.*;
import games.spaceInvaders.*;
import games.racinggame.*;

/**
 *
 * @author 91809
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        typinggameButton = new javax.swing.JButton();
        spaceInvadersButton = new javax.swing.JButton();
        flappyBirdButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        statsButton = new javax.swing.JButton();
        snakegameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 12, 55));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(25, 12, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/menu-banner.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 420));

        jLabel7.setBackground(new java.awt.Color(25, 12, 55));
        jLabel7.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ultimate Games");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 200, 80));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(430, 0, 420, 600);

        jPanel3.setBackground(new java.awt.Color(25, 12, 55));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typinggameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/typing-game.jpg"))); // NOI18N
        typinggameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        typinggameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typinggameButtonActionPerformed(evt);
            }
        });
        jPanel3.add(typinggameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 160, 160));

        spaceInvadersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/space-invaders.jpg"))); // NOI18N
        spaceInvadersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spaceInvadersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceInvadersButtonActionPerformed(evt);
            }
        });
        jPanel3.add(spaceInvadersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, 160));

        flappyBirdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/flappybird-game.jpg"))); // NOI18N
        flappyBirdButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flappyBirdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flappyBirdButtonActionPerformed(evt);
            }
        });
        jPanel3.add(flappyBirdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 160));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLAY GAMES");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, 60));

        statsButton.setBackground(new java.awt.Color(255, 255, 255));
        statsButton.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        statsButton.setForeground(new java.awt.Color(25, 12, 55));
        statsButton.setText("STATS");
        statsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        jPanel3.add(statsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 160, 50));

        snakegameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/snake-game.jpg"))); // NOI18N
        snakegameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        snakegameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snakegameButtonActionPerformed(evt);
            }
        });
        jPanel3.add(snakegameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 160));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 430, 600);

        setBounds(0, 0, 864, 605);
    }// </editor-fold>//GEN-END:initComponents

    private void typinggameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typinggameButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new RacingGame();
    }//GEN-LAST:event_typinggameButtonActionPerformed

    private void spaceInvadersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceInvadersButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new SpaceInvaders();
    }//GEN-LAST:event_spaceInvadersButtonActionPerformed

    private void flappyBirdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flappyBirdButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new FlappyBirdGame();
    }//GEN-LAST:event_flappyBirdButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Stats().setVisible(true);
    }//GEN-LAST:event_statsButtonActionPerformed

    private void snakegameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snakegameButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new GameFrame();
    }//GEN-LAST:event_snakegameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton flappyBirdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton snakegameButton;
    private javax.swing.JButton spaceInvadersButton;
    private javax.swing.JButton statsButton;
    private javax.swing.JButton typinggameButton;
    // End of variables declaration//GEN-END:variables
}
