
package games;
import games.UserSession;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91809
 */
public class Stats extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/games";
    private static final String USER = "root";
    private static final String PASSWORD = "root";
    public Stats() {
        initComponents();
        tableCreation();
        setLocationRelativeTo(null);
    }
    
    public void tableCreation() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Game", "Score", "Date"}, 0);
        table.setModel(model);
        table.setFont(new Font("Arial", Font.PLAIN, 16));
        table.setRowHeight(30);
        table.setFillsViewportHeight(true);
        table.setSelectionBackground(new Color(173, 216, 230)); // Light Blue
        table.setSelectionForeground(Color.BLACK);

        
        List<Integer> scoreList = new ArrayList<>();
        List<Timestamp> dateList = new ArrayList<>();
        List<String> gameList = new ArrayList<>();
        loadPreviousRaces(model, scoreList, dateList, gameList);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        snakeMaxScore = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        snakeAvgScore = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spaceMaxScore = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spaceAvgScore = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        typingMaxScore = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        typingAvgScore = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        flappyMaxScore = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        flappyAvgScore = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY SCORES");

        jLabel15.setText("Max. Score");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Sname Game");

        jLabel17.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel17.setText("0");

        jLabel18.setText("Avg. Score");

        jLabel19.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel19.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(14, 25, 43));

        table.setBackground(new java.awt.Color(14, 25, 43));
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setGridColor(new java.awt.Color(14, 25, 43));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 870, 410));

        jPanel1.setBackground(new java.awt.Color(14, 25, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Max. Score");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sname Game");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 40));

        snakeMaxScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        snakeMaxScore.setForeground(new java.awt.Color(255, 255, 255));
        snakeMaxScore.setText("0");
        jPanel1.add(snakeMaxScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Avg. Score");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, 30));

        snakeAvgScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        snakeAvgScore.setForeground(new java.awt.Color(255, 255, 255));
        snakeAvgScore.setText("0");
        jPanel1.add(snakeAvgScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Max. Score");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Space Invaders Game");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 210, 40));

        spaceMaxScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        spaceMaxScore.setForeground(new java.awt.Color(255, 255, 255));
        spaceMaxScore.setText("0");
        jPanel1.add(spaceMaxScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Avg. Score");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 30));

        spaceAvgScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        spaceAvgScore.setForeground(new java.awt.Color(255, 255, 255));
        spaceAvgScore.setText("0");
        jPanel1.add(spaceAvgScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Max. Score");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 90, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Type Racing Game");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 200, 40));

        typingMaxScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        typingMaxScore.setForeground(new java.awt.Color(255, 255, 255));
        typingMaxScore.setText("0");
        jPanel1.add(typingMaxScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 90, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Avg. Score");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 90, 30));

        typingAvgScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        typingAvgScore.setForeground(new java.awt.Color(255, 255, 255));
        typingAvgScore.setText("0");
        jPanel1.add(typingAvgScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 90, 30));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Max. Score");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 90, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Flappy Bird Game");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 200, 40));

        flappyMaxScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        flappyMaxScore.setForeground(new java.awt.Color(255, 255, 255));
        flappyMaxScore.setText("0");
        jPanel1.add(flappyMaxScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 90, 30));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Avg. Score");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 90, 30));

        flappyAvgScore.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        flappyAvgScore.setForeground(new java.awt.Color(255, 255, 255));
        flappyAvgScore.setText("0");
        jPanel1.add(flappyAvgScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 870, 100));

        jPanel2.setBackground(new java.awt.Color(14, 25, 43));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/stats.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 120));

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("THE ULTIMATE SHOWDOWN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 640, 70));

        menuButton.setBackground(new java.awt.Color(51, 51, 51));
        menuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Menu");
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.setFocusable(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        jPanel2.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuPage().setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void loadPreviousRaces(DefaultTableModel model, List<Integer> scoreList, List<Timestamp> dateList, List<String> gameList) {
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);

            String query = "SELECT * FROM user_scores WHERE player_name = ?";
            statement = connection.prepareStatement(query);
            statement.setString(1, UserSession.getInstance().getUsername()); // Fetch results for the current user

            resultSet = statement.executeQuery();
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String playerName = resultSet.getString("player_name");
                int score = resultSet.getInt("score");
                String game = resultSet.getString("game");
                Timestamp date = resultSet.getTimestamp("date");

                model.addRow(new Object[]{id, game, score, date});

                // Add WPM and Date to lists for chart plotting
                scoreList.add(score);
                gameList.add(game);
                dateList.add(date);
            }
            query = "select game, avg(score) as avg_score, max(score) as max_score from user_scores where player_name = ? group by game";
            
            statement = connection.prepareStatement(query);
            statement.setString(1, UserSession.getInstance().getUsername()); // Fetch results for the current user

            resultSet = statement.executeQuery();
            while (resultSet.next()) {
                int max_score = resultSet.getInt("avg_score");
                Float avg_score = resultSet.getFloat("max_score");
                String game = resultSet.getString("game");

                if(game.equals("Snake")) {
                    snakeAvgScore.setText(avg_score + "");
                    snakeMaxScore.setText(max_score + "");
                }
                if(game.equals("Space Invaders")) {
                    spaceAvgScore.setText(avg_score + "");
                    spaceMaxScore.setText(max_score + "");
                }
                if(game.equals("Flappy Bird")) {
                    flappyAvgScore.setText(avg_score + "");
                    flappyMaxScore.setText(max_score + "");
                }
                if(game.equals("Type Racing")) {
                    typingAvgScore.setText(avg_score + "");
                    typingMaxScore.setText(max_score + "");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel flappyAvgScore;
    private javax.swing.JLabel flappyMaxScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel snakeAvgScore;
    private javax.swing.JLabel snakeMaxScore;
    private javax.swing.JLabel spaceAvgScore;
    private javax.swing.JLabel spaceMaxScore;
    private javax.swing.JTable table;
    private javax.swing.JLabel typingAvgScore;
    private javax.swing.JLabel typingMaxScore;
    // End of variables declaration//GEN-END:variables
}
